### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by jverkoey** [jasper-seinhorst/homebridge-porsche-taycan#1]
Are you running into similar issues as the ones I'm trying to document in https://github.com/driven-app/porsche-connect/issues/160 ? Wondering if you've having any luck with the root cause analysis!

**Comment by jasper-seinhorst** [comment]
Yes, issue is/was in this application. I added a 5 times retry for now which fixes most issues. Lets discus on Discord about a proper solution for both applications
