### ISSUE TITLE
Unable to identify proxy error

### ISSUE THREAD

**Issue by itskeKs** [jasper-seinhorst/homebridge-porsche-taycan#3]
I get the following error when i try to connect my new Macan EV through the plugin.

And would it also be possible to add honking and blinking into the plugin. What i want to do is, to install a motion sensor near the car and create some automations when someone is near the car when its parked at home. Would that work? Looks like the API does provide sich info?!

![IMG_0392](https://github.com/user-attachments/assets/95ecabb9-9418-42a7-9a0c-455c8ac6f891)

**Comment by jasper-seinhorst** [comment]
Hi @itskeKs Just a heads-up that the Porsche API has been deprecated, and unfortunately, there isn’t an alternative available right now. I'm planning to use the API used by the MyPorsche mobile app, but I don't have a planning yet.
